package com.aurospaces.neighbourhood.bean;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;



import java.util.Date;
import java.math.BigDecimal;


/**
 *
 * @author autogenerated
 */



public class ItemsBean 
{

protected int id   = 0;

protected Date createdTime ;

protected Date updatedTime ;

protected String name ;

protected String description ;

protected String price ;
protected String discount ;

protected String status ;
protected String itemstatus ;

public String getItemstatus() {
	return itemstatus;
}
public void setItemstatus(String itemstatus) {
	this.itemstatus = itemstatus;
}
public int getId()
{
  return id;
}
public void setId(final int id)
{
  this.id = id;
}
public Date getCreatedTime()
{
  return createdTime;
}
public void setCreatedTime(final Date createdTime)
{
  this.createdTime = createdTime;
}
public Date getUpdatedTime()
{
  return updatedTime;
}
public void setUpdatedTime(final Date updatedTime)
{
  this.updatedTime = updatedTime;
}
public String getName()
{
  return name;
}
public void setName(final String name)
{
  this.name = name;
}
public String getDescription()
{
  return description;
}
public void setDescription(final String description)
{
  this.description = description;
}
public String getStatus()
{
  return status;
}
public void setStatus(final String status)
{
  this.status = status;
}
public String getPrice() {
	return price;
}
public void setPrice(String price) {
	this.price = price;
}
public String getDiscount() {
	return discount;
}
public void setDiscount(String discount) {
	this.discount = discount;
}
@Override
public String toString() {
	return "ItemsBean [id=" + id + ", createdTime=" + createdTime + ", updatedTime=" + updatedTime + ", name=" + name
			+ ", description=" + description + ", price=" + price + ", discount=" + discount + ", status=" + status
			+ "]";
}


}